// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react";

const Dashboard: React.FC = () => {
  return (
    <div>
      <h2>Dashboard</h2>
      <p>Welcome to the protected dashboard!</p>
    </div>
  );
};

export default Dashboard;
